export const baseURL:string = 'https://upayments-studycase-api.herokuapp.com/api/products/';
export const bearer_token:string = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QudHVyazA2QGdtYWlsLmNvbSIsImdpdGh1YiI6Imh0dHBzOi8vZ2l0aHViLmNvbS9VbGZ0S2N5IiwiaWF0IjoxNjY2MjU4MTYyLCJleHAiOjE2NjY2OTAxNjJ9.uSDp1gPzHqNgToDu1BLH-B7hFg7MDZY71g21ZLT1EM0';

